## Create the conda environment using this file with the command:
# conda env create -f environment.yaml

## Install the package in editable mode with the command:
# conda activate <your-environment-name>
# pip install -e .
# conda env update -f environment.yaml

name: seacharts
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.12, <3.14
  - gdal
  - fiona
  - pip
  - pip:
    - -r requirements.no_gdal.txt